# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('github', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('personalsite', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=b'')),
                ('tshirt', models.CharField(choices=[(b'XS', b'extra small'), (b'S', b'small'), (b'M', b'medium'), (b'L', b'large'), (b'XL', b'extra large')], max_length=4)),
                ('travel_reinbursement', models.BooleanField()),
                ('first_hackathon', models.BooleanField()),
                ('mentor', models.BooleanField()),
                ('reason', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, b'applied'), (1, b'accepted'), (2, b'waitlisted'), (3, b'rejected')], default=0)),
            ],
        ),
    ]
