# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwhacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='personalsite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
